apiVersion: v1
kind: Namespace
metadata:
  name: monolith-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-app-deployment
  namespace: monolith-app
  labels:
    app: monolith-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monolith-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: monolith-app
    spec:
      containers:
      - name: monolith-app
        image: ingihome/monolith-exersice-api:latest
---
apiVersion: v1
kind: Service
metadata:
  name: monolith-app-svc
  namespace: monolith-app
  labels:
    app: monolith-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"    
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: monolith-app